apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  interval: 5m
  targetNamespace: crossplane-system
  chart:
    spec:
      chart: crossplane
      version: "1.14.0"      
      sourceRef:
        kind: HelmRepository
        name: crossplane-stable
        namespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    args:
      - --enable-composition-functions
