apiVersion: iam.aws.crossplane.io/v1beta1
kind: Role
metadata:
  name: msk-connect-core-edge-role-prod
spec:
  forProvider:
    assumeRolePolicyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {"Effect":"Allow","Principal":{"Service":"kafkaconnect.amazonaws.com"},"Action":"sts:AssumeRole"}
        ]
      }
  providerConfigRef:
    name: aws-default

---

apiVersion: iam.aws.crossplane.io/v1beta1
kind: Policy
metadata:
  name: msk-connect-core-edge-policy-prod
spec:
  forProvider:
    name: msk-connect-core-edge-policy-prod
    document: |
      {
        "Version":"2012-10-17",
        "Statement":[
          { "Effect":"Allow",
            "Action":[
              "ec2:CreateNetworkInterface","ec2:DescribeNetworkInterfaces","ec2:DeleteNetworkInterface",
              "ec2:DescribeSubnets","ec2:DescribeVpcs","ec2:DescribeSecurityGroups"
            ],
            "Resource":"*"
          },
          { "Effect":"Allow",
            "Action":[ "secretsmanager:GetSecretValue","secretsmanager:DescribeSecret" ],
            "Resource":"arn:aws:secretsmanager:<<region>>:<<account_id>>:secret:*"
          }
        ]
      }
  providerConfigRef:
    name: aws-default

---

apiVersion: iam.aws.crossplane.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: msk-connect-core-edge-attach-prod
spec:
  forProvider:
    roleNameRef:
      name: msk-connect-core-edge-role
    policyArnRef:
      name: msk-connect-core-edge-policy
  providerConfigRef:
    name: aws-default
