apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: sparkApp
  namespace: flux-system
spec:
  secretRef:
    name: docker-registry
  image: <ECR Repo URL here>
  interval: 1m
