apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: namespaces
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra-ops/external-secrets/operator
  prune: true
  wait: true
  timeout: 5m0s
